// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;


/**
 * <pre>
 *test1
 * </pre>
 *
 * Protobuf type {@code com.jin.proto.HelloRequest}
 */
public  final class HelloRequest extends
    com.google.protobuf.GeneratedMessageLite<HelloRequest, HelloRequest.Builder> implements HelloRequestOrBuilder {


  private HelloRequest() {
    username_ = "";
    bytesData_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int USERNAME_FIELD_NUMBER = 1;
  private String username_;
  /**
   * <code>optional string username = 1;</code>
   */
  public String getUsername() {
    return username_;
  }
  /**
   * <code>optional string username = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>optional string username = 1;</code>
   */
  private void setUsername(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    username_ = value;
  }
  /**
   * <code>optional string username = 1;</code>
   */
  private void clearUsername() {

    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>optional string username = 1;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    username_ = value.toStringUtf8();
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>optional int32 age = 2;</code>
   */
  public int getAge() {
    return age_;
  }
  /**
   * <code>optional int32 age = 2;</code>
   */
  private void setAge(int value) {

    age_ = value;
  }
  /**
   * <code>optional int32 age = 2;</code>
   */
  private void clearAge() {

    age_ = 0;
  }

  public static final int ANYDATA_FIELD_NUMBER = 3;
  private com.google.protobuf.Any anyData_;
  /**
   * <code>optional .google.protobuf.Any anyData = 3;</code>
   */
  public boolean hasAnyData() {
    return anyData_ != null;
  }
  /**
   * <code>optional .google.protobuf.Any anyData = 3;</code>
   */
  public com.google.protobuf.Any getAnyData() {
    return anyData_ == null ? com.google.protobuf.Any.getDefaultInstance() : anyData_;
  }
  /**
   * <code>optional .google.protobuf.Any anyData = 3;</code>
   */
  private void setAnyData(com.google.protobuf.Any value) {
    if (value == null) {
      throw new NullPointerException();
    }
    anyData_ = value;

    }
  /**
   * <code>optional .google.protobuf.Any anyData = 3;</code>
   */
  private void setAnyData(
      com.google.protobuf.Any.Builder builderForValue) {
    anyData_ = builderForValue.build();

  }
  /**
   * <code>optional .google.protobuf.Any anyData = 3;</code>
   */
  private void mergeAnyData(com.google.protobuf.Any value) {
    if (anyData_ != null &&
        anyData_ != com.google.protobuf.Any.getDefaultInstance()) {
      anyData_ =
        com.google.protobuf.Any.newBuilder(anyData_).mergeFrom(value).buildPartial();
    } else {
      anyData_ = value;
    }

  }
  /**
   * <code>optional .google.protobuf.Any anyData = 3;</code>
   */
  private void clearAnyData() {  anyData_ = null;

  }

  public static final int BYTESDATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString bytesData_;
  /**
   * <code>optional bytes bytesData = 4;</code>
   */
  public com.google.protobuf.ByteString getBytesData() {
    return bytesData_;
  }
  /**
   * <code>optional bytes bytesData = 4;</code>
   */
  private void setBytesData(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }

    bytesData_ = value;
  }
  /**
   * <code>optional bytes bytesData = 4;</code>
   */
  private void clearBytesData() {

    bytesData_ = getDefaultInstance().getBytesData();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!username_.isEmpty()) {
      output.writeString(1, getUsername());
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (anyData_ != null) {
      output.writeMessage(3, getAnyData());
    }
    if (!bytesData_.isEmpty()) {
      output.writeBytes(4, bytesData_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!username_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getUsername());
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (anyData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAnyData());
    }
    if (!bytesData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, bytesData_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.realtime.grpc.protocode.HelloRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.HelloRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.realtime.grpc.protocode.HelloRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   *test1
   * </pre>
   *
   * Protobuf type {@code com.jin.proto.HelloRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        HelloRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.jin.proto.HelloRequest)
      com.realtime.grpc.protocode.HelloRequestOrBuilder {
    // Construct using com.realtime.grpc.protocode.HelloRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string username = 1;</code>
     */
    public String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public Builder setUsername(
        String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return instance.getAge();
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public Builder setAge(int value) {
      copyOnWrite();
      instance.setAge(value);
      return this;
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public Builder clearAge() {
      copyOnWrite();
      instance.clearAge();
      return this;
    }

    /**
     * <code>optional .google.protobuf.Any anyData = 3;</code>
     */
    public boolean hasAnyData() {
      return instance.hasAnyData();
    }
    /**
     * <code>optional .google.protobuf.Any anyData = 3;</code>
     */
    public com.google.protobuf.Any getAnyData() {
      return instance.getAnyData();
    }
    /**
     * <code>optional .google.protobuf.Any anyData = 3;</code>
     */
    public Builder setAnyData(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.setAnyData(value);
      return this;
      }
    /**
     * <code>optional .google.protobuf.Any anyData = 3;</code>
     */
    public Builder setAnyData(
        com.google.protobuf.Any.Builder builderForValue) {
      copyOnWrite();
      instance.setAnyData(builderForValue);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Any anyData = 3;</code>
     */
    public Builder mergeAnyData(com.google.protobuf.Any value) {
      copyOnWrite();
      instance.mergeAnyData(value);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Any anyData = 3;</code>
     */
    public Builder clearAnyData() {  copyOnWrite();
      instance.clearAnyData();
      return this;
    }

    /**
     * <code>optional bytes bytesData = 4;</code>
     */
    public com.google.protobuf.ByteString getBytesData() {
      return instance.getBytesData();
    }
    /**
     * <code>optional bytes bytesData = 4;</code>
     */
    public Builder setBytesData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBytesData(value);
      return this;
    }
    /**
     * <code>optional bytes bytesData = 4;</code>
     */
    public Builder clearBytesData() {
      copyOnWrite();
      instance.clearBytesData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.jin.proto.HelloRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.realtime.grpc.protocode.HelloRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.realtime.grpc.protocode.HelloRequest other = (com.realtime.grpc.protocode.HelloRequest) arg1;
        username_ = visitor.visitString(!username_.isEmpty(), username_,
            !other.username_.isEmpty(), other.username_);
        age_ = visitor.visitInt(age_ != 0, age_,
            other.age_ != 0, other.age_);
        anyData_ = visitor.visitMessage(anyData_, other.anyData_);
        bytesData_ = visitor.visitByteString(bytesData_ != com.google.protobuf.ByteString.EMPTY, bytesData_,
            other.bytesData_ != com.google.protobuf.ByteString.EMPTY, other.bytesData_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                username_ = s;
                break;
              }
              case 16: {

                age_ = input.readInt32();
                break;
              }
              case 26: {
                com.google.protobuf.Any.Builder subBuilder = null;
                if (anyData_ != null) {
                  subBuilder = anyData_.toBuilder();
                }
                anyData_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(anyData_);
                  anyData_ = subBuilder.buildPartial();
                }

                break;
              }
              case 34: {

                bytesData_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.realtime.grpc.protocode.HelloRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.jin.proto.HelloRequest)
  private static final com.realtime.grpc.protocode.HelloRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HelloRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.realtime.grpc.protocode.HelloRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HelloRequest> PARSER;

  public static com.google.protobuf.Parser<HelloRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

