// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;

/**
 * Protobuf type {@code com.jin.proto.HelloResponse}
 */
public final class HelloResponse extends
        com.google.protobuf.GeneratedMessageLite<
                HelloResponse, HelloResponse.Builder> implements
        // @@protoc_insertion_point(message_implements:com.jin.proto.HelloResponse)
        HelloResponseOrBuilder {

    private HelloResponse() {
        username_ = "";
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private String username_;

    /**
     * <code>optional string username = 1;</code>
     */
    public String getUsername() {
        return username_;
    }

    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
    getUsernameBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(username_);
    }

    /**
     * <code>optional string username = 1;</code>
     */
    private void setUsername(
            String value) {
        if (value == null) {
            throw new NullPointerException();
        }

        username_ = value;
    }

    /**
     * <code>optional string username = 1;</code>
     */
    private void clearUsername() {

        username_ = getDefaultInstance().getUsername();
    }

    /**
     * <code>optional string username = 1;</code>
     */
    private void setUsernameBytes(
            com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        username_ = value.toStringUtf8();
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;

    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
        return age_;
    }

    /**
     * <code>optional int32 age = 2;</code>
     */
    private void setAge(int value) {

        age_ = value;
    }

    /**
     * <code>optional int32 age = 2;</code>
     */
    private void clearAge() {

        age_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!username_.isEmpty()) {
            output.writeString(1, getUsername());
        }
        if (age_ != 0) {
            output.writeInt32(2, age_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!username_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeStringSize(1, getUsername());
        }
        if (age_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, age_);
        }
        memoizedSerializedSize = size;
        return size;
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static com.realtime.grpc.protocode.HelloResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.realtime.grpc.protocode.HelloResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.jin.proto.HelloResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    HelloResponse, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.jin.proto.HelloResponse)
            com.realtime.grpc.protocode.HelloResponseOrBuilder {
        // Construct using com.realtime.grpc.protocode.HelloResponse.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string username = 1;</code>
         */
        public String getUsername() {
            return instance.getUsername();
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            return instance.getUsernameBytes();
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public Builder setUsername(
                String value) {
            copyOnWrite();
            instance.setUsername(value);
            return this;
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public Builder clearUsername() {
            copyOnWrite();
            instance.clearUsername();
            return this;
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public Builder setUsernameBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setUsernameBytes(value);
            return this;
        }

        /**
         * <code>optional int32 age = 2;</code>
         */
        public int getAge() {
            return instance.getAge();
        }

        /**
         * <code>optional int32 age = 2;</code>
         */
        public Builder setAge(int value) {
            copyOnWrite();
            instance.setAge(value);
            return this;
        }

        /**
         * <code>optional int32 age = 2;</code>
         */
        public Builder clearAge() {
            copyOnWrite();
            instance.clearAge();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.jin.proto.HelloResponse)
    }

    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new com.realtime.grpc.protocode.HelloResponse();
            }
            case IS_INITIALIZED: {
                return DEFAULT_INSTANCE;
            }
            case MAKE_IMMUTABLE: {
                return null;
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case VISIT: {
                Visitor visitor = (Visitor) arg0;
                com.realtime.grpc.protocode.HelloResponse other = (com.realtime.grpc.protocode.HelloResponse) arg1;
                username_ = visitor.visitString(!username_.isEmpty(), username_,
                        !other.username_.isEmpty(), other.username_);
                age_ = visitor.visitInt(age_ != 0, age_,
                        other.age_ != 0, other.age_);
                if (visitor == MergeFromVisitor
                        .INSTANCE) {
                }
                return this;
            }
            case MERGE_FROM_STREAM: {
                com.google.protobuf.CodedInputStream input =
                        (com.google.protobuf.CodedInputStream) arg0;
                com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                        (com.google.protobuf.ExtensionRegistryLite) arg1;
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!input.skipField(tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 10: {
                                String s = input.readStringRequireUtf8();

                                username_ = s;
                                break;
                            }
                            case 16: {

                                age_ = input.readInt32();
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw new RuntimeException(e.setUnfinishedMessage(this));
                } catch (java.io.IOException e) {
                    throw new RuntimeException(
                            new com.google.protobuf.InvalidProtocolBufferException(
                                    e.getMessage()).setUnfinishedMessage(this));
                } finally {
                }
            }
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                if (PARSER == null) {
                    synchronized (com.realtime.grpc.protocode.HelloResponse.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                }
                return PARSER;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.jin.proto.HelloResponse)
    private static final com.realtime.grpc.protocode.HelloResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new HelloResponse();
        DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.realtime.grpc.protocode.HelloResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HelloResponse> PARSER;

    public static com.google.protobuf.Parser<HelloResponse> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

