// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jin.proto.HelloResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional int32 age = 2;</code>
   */
  int getAge();
}
