// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;

/**
 * Protobuf type {@code com.realtime.grpc.protocode.StreamResponse}
 */
public  final class StreamResponse extends
    com.google.protobuf.GeneratedMessageLite<
            StreamResponse, StreamResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:com.realtime.grpc.protocode.StreamResponse)
        StreamResponseOrBuilder {
  private StreamResponse() {
    responseInfo_ = "";
    uUID_ = "";
  }
  public static final int RESPONSEINFO_FIELD_NUMBER = 1;
  private String responseInfo_;
  /**
   * <code>optional string responseInfo = 1;</code>
   */
  public String getResponseInfo() {
    return responseInfo_;
  }
  /**
   * <code>optional string responseInfo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResponseInfoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(responseInfo_);
  }
  /**
   * <code>optional string responseInfo = 1;</code>
   */
  private void setResponseInfo(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    responseInfo_ = value;
  }
  /**
   * <code>optional string responseInfo = 1;</code>
   */
  private void clearResponseInfo() {

    responseInfo_ = getDefaultInstance().getResponseInfo();
  }
  /**
   * <code>optional string responseInfo = 1;</code>
   */
  private void setResponseInfoBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    responseInfo_ = value.toStringUtf8();
  }

  public static final int RECEIVETIME_FIELD_NUMBER = 2;
  private long receiveTime_;
  /**
   * <code>optional int64 receiveTime = 2;</code>
   */
  public long getReceiveTime() {
    return receiveTime_;
  }
  /**
   * <code>optional int64 receiveTime = 2;</code>
   */
  private void setReceiveTime(long value) {

    receiveTime_ = value;
  }
  /**
   * <code>optional int64 receiveTime = 2;</code>
   */
  private void clearReceiveTime() {

    receiveTime_ = 0L;
  }

  public static final int UUID_FIELD_NUMBER = 3;
  private String uUID_;
  /**
   * <code>optional string UUID = 3;</code>
   */
  public String getUUID() {
    return uUID_;
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUUIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uUID_);
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  private void setUUID(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    uUID_ = value;
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  private void clearUUID() {

    uUID_ = getDefaultInstance().getUUID();
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  private void setUUIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    uUID_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!responseInfo_.isEmpty()) {
      output.writeString(1, getResponseInfo());
    }
    if (receiveTime_ != 0L) {
      output.writeInt64(2, receiveTime_);
    }
    if (!uUID_.isEmpty()) {
      output.writeString(3, getUUID());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!responseInfo_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getResponseInfo());
    }
    if (receiveTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, receiveTime_);
    }
    if (!uUID_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getUUID());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.realtime.grpc.protocode.StreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.realtime.grpc.protocode.StreamResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code com.realtime.grpc.protocode.StreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        StreamResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.realtime.grpc.protocode.StreamResponse)
      com.realtime.grpc.protocode.StreamResponseOrBuilder {
    // Construct using com.realtime.grpc.protocode.StreamResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string responseInfo = 1;</code>
     */
    public String getResponseInfo() {
      return instance.getResponseInfo();
    }
    /**
     * <code>optional string responseInfo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseInfoBytes() {
      return instance.getResponseInfoBytes();
    }
    /**
     * <code>optional string responseInfo = 1;</code>
     */
    public Builder setResponseInfo(
        String value) {
      copyOnWrite();
      instance.setResponseInfo(value);
      return this;
    }
    /**
     * <code>optional string responseInfo = 1;</code>
     */
    public Builder clearResponseInfo() {
      copyOnWrite();
      instance.clearResponseInfo();
      return this;
    }
    /**
     * <code>optional string responseInfo = 1;</code>
     */
    public Builder setResponseInfoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResponseInfoBytes(value);
      return this;
    }

    /**
     * <code>optional int64 receiveTime = 2;</code>
     */
    public long getReceiveTime() {
      return instance.getReceiveTime();
    }
    /**
     * <code>optional int64 receiveTime = 2;</code>
     */
    public Builder setReceiveTime(long value) {
      copyOnWrite();
      instance.setReceiveTime(value);
      return this;
    }
    /**
     * <code>optional int64 receiveTime = 2;</code>
     */
    public Builder clearReceiveTime() {
      copyOnWrite();
      instance.clearReceiveTime();
      return this;
    }

    /**
     * <code>optional string UUID = 3;</code>
     */
    public String getUUID() {
      return instance.getUUID();
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      return instance.getUUIDBytes();
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public Builder setUUID(
        String value) {
      copyOnWrite();
      instance.setUUID(value);
      return this;
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public Builder clearUUID() {
      copyOnWrite();
      instance.clearUUID();
      return this;
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public Builder setUUIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUUIDBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.realtime.grpc.protocode.StreamResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.realtime.grpc.protocode.StreamResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.realtime.grpc.protocode.StreamResponse other = (com.realtime.grpc.protocode.StreamResponse) arg1;
        responseInfo_ = visitor.visitString(!responseInfo_.isEmpty(), responseInfo_,
            !other.responseInfo_.isEmpty(), other.responseInfo_);
        receiveTime_ = visitor.visitLong(receiveTime_ != 0L, receiveTime_,
            other.receiveTime_ != 0L, other.receiveTime_);
        uUID_ = visitor.visitString(!uUID_.isEmpty(), uUID_,
            !other.uUID_.isEmpty(), other.uUID_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                responseInfo_ = s;
                break;
              }
              case 16: {

                receiveTime_ = input.readInt64();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                uUID_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.realtime.grpc.protocode.StreamResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.realtime.grpc.protocode.StreamResponse)
  private static final com.realtime.grpc.protocode.StreamResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StreamResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.realtime.grpc.protocode.StreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StreamResponse> PARSER;

  public static com.google.protobuf.Parser<StreamResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

