// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;

/**
 * <pre>
 *test 4
 * </pre>
 *
 * Protobuf type {@code com.realtime.grpc.protocode.StreamRequest}
 */
public  final class StreamRequest extends
    com.google.protobuf.GeneratedMessageLite<
            StreamRequest, StreamRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:com.realtime.grpc.protocode.StreamRequest)
        StreamRequestOrBuilder {
  private StreamRequest() {
    requestInfo_ = "";
    uUID_ = "";
  }
  public static final int REQUESTINFO_FIELD_NUMBER = 1;
  private String requestInfo_;
  /**
   * <code>optional string requestInfo = 1;</code>
   */
  public String getRequestInfo() {
    return requestInfo_;
  }
  /**
   * <code>optional string requestInfo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequestInfoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(requestInfo_);
  }
  /**
   * <code>optional string requestInfo = 1;</code>
   */
  private void setRequestInfo(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    requestInfo_ = value;
  }
  /**
   * <code>optional string requestInfo = 1;</code>
   */
  private void clearRequestInfo() {

    requestInfo_ = getDefaultInstance().getRequestInfo();
  }
  /**
   * <code>optional string requestInfo = 1;</code>
   */
  private void setRequestInfoBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    requestInfo_ = value.toStringUtf8();
  }

  public static final int REQUESTTIME_FIELD_NUMBER = 2;
  private long requestTime_;
  /**
   * <code>optional int64 requestTime = 2;</code>
   */
  public long getRequestTime() {
    return requestTime_;
  }
  /**
   * <code>optional int64 requestTime = 2;</code>
   */
  private void setRequestTime(long value) {

    requestTime_ = value;
  }
  /**
   * <code>optional int64 requestTime = 2;</code>
   */
  private void clearRequestTime() {

    requestTime_ = 0L;
  }

  public static final int UUID_FIELD_NUMBER = 3;
  private String uUID_;
  /**
   * <code>optional string UUID = 3;</code>
   */
  public String getUUID() {
    return uUID_;
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUUIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uUID_);
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  private void setUUID(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    uUID_ = value;
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  private void clearUUID() {

    uUID_ = getDefaultInstance().getUUID();
  }
  /**
   * <code>optional string UUID = 3;</code>
   */
  private void setUUIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    uUID_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!requestInfo_.isEmpty()) {
      output.writeString(1, getRequestInfo());
    }
    if (requestTime_ != 0L) {
      output.writeInt64(2, requestTime_);
    }
    if (!uUID_.isEmpty()) {
      output.writeString(3, getUUID());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!requestInfo_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getRequestInfo());
    }
    if (requestTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, requestTime_);
    }
    if (!uUID_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getUUID());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.realtime.grpc.protocode.StreamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.realtime.grpc.protocode.StreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.realtime.grpc.protocode.StreamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   *test 4
   * </pre>
   *
   * Protobuf type {@code com.realtime.grpc.protocode.StreamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        StreamRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.realtime.grpc.protocode.StreamRequest)
      com.realtime.grpc.protocode.StreamRequestOrBuilder {
    // Construct using com.realtime.grpc.protocode.StreamRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string requestInfo = 1;</code>
     */
    public String getRequestInfo() {
      return instance.getRequestInfo();
    }
    /**
     * <code>optional string requestInfo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestInfoBytes() {
      return instance.getRequestInfoBytes();
    }
    /**
     * <code>optional string requestInfo = 1;</code>
     */
    public Builder setRequestInfo(
        String value) {
      copyOnWrite();
      instance.setRequestInfo(value);
      return this;
    }
    /**
     * <code>optional string requestInfo = 1;</code>
     */
    public Builder clearRequestInfo() {
      copyOnWrite();
      instance.clearRequestInfo();
      return this;
    }
    /**
     * <code>optional string requestInfo = 1;</code>
     */
    public Builder setRequestInfoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRequestInfoBytes(value);
      return this;
    }

    /**
     * <code>optional int64 requestTime = 2;</code>
     */
    public long getRequestTime() {
      return instance.getRequestTime();
    }
    /**
     * <code>optional int64 requestTime = 2;</code>
     */
    public Builder setRequestTime(long value) {
      copyOnWrite();
      instance.setRequestTime(value);
      return this;
    }
    /**
     * <code>optional int64 requestTime = 2;</code>
     */
    public Builder clearRequestTime() {
      copyOnWrite();
      instance.clearRequestTime();
      return this;
    }

    /**
     * <code>optional string UUID = 3;</code>
     */
    public String getUUID() {
      return instance.getUUID();
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      return instance.getUUIDBytes();
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public Builder setUUID(
        String value) {
      copyOnWrite();
      instance.setUUID(value);
      return this;
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public Builder clearUUID() {
      copyOnWrite();
      instance.clearUUID();
      return this;
    }
    /**
     * <code>optional string UUID = 3;</code>
     */
    public Builder setUUIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUUIDBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.realtime.grpc.protocode.StreamRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.realtime.grpc.protocode.StreamRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.realtime.grpc.protocode.StreamRequest other = (com.realtime.grpc.protocode.StreamRequest) arg1;
        requestInfo_ = visitor.visitString(!requestInfo_.isEmpty(), requestInfo_,
            !other.requestInfo_.isEmpty(), other.requestInfo_);
        requestTime_ = visitor.visitLong(requestTime_ != 0L, requestTime_,
            other.requestTime_ != 0L, other.requestTime_);
        uUID_ = visitor.visitString(!uUID_.isEmpty(), uUID_,
            !other.uUID_.isEmpty(), other.uUID_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                requestInfo_ = s;
                break;
              }
              case 16: {

                requestTime_ = input.readInt64();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                uUID_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.realtime.grpc.protocode.StreamRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.realtime.grpc.protocode.StreamRequest)
  private static final com.realtime.grpc.protocode.StreamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StreamRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.realtime.grpc.protocode.StreamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StreamRequest> PARSER;

  public static com.google.protobuf.Parser<StreamRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

