// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.realtime.grpc.protocode.StreamRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string requestInfo = 1;</code>
   */
  String getRequestInfo();
  /**
   * <code>optional string requestInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();

  /**
   * <code>optional int64 requestTime = 2;</code>
   */
  long getRequestTime();

  /**
   * <code>optional string UUID = 3;</code>
   */
  String getUUID();
  /**
   * <code>optional string UUID = 3;</code>
   */
  com.google.protobuf.ByteString
      getUUIDBytes();
}
