// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.realtime.grpc.protocode;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.realtime.grpc.protocode.StreamResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string responseInfo = 1;</code>
   */
  String getResponseInfo();
  /**
   * <code>optional string responseInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();

  /**
   * <code>optional int64 receiveTime = 2;</code>
   */
  long getReceiveTime();

  /**
   * <code>optional string UUID = 3;</code>
   */
  String getUUID();
  /**
   * <code>optional string UUID = 3;</code>
   */
  com.google.protobuf.ByteString
      getUUIDBytes();
}
